
serverAddr = "8.141.86.102"
serverPort = 15443

auth.method = "token"
auth.token = "mapyeah"



transport.heartbeatInterval = 30


transport.heartbeatTimeout = 90



log.to = "frpc.log"
log.level = "info"
log.maxDays = 3
webServer.addr = "127.0.0.1"
webServer.port = 57400
transport.tls.enable = false

  
  
  
  





[[proxies]]
name = "nas"

type = "https"

localIP = "192.168.1.12"
localPort = 5001
customDomains=[""]
subdomain="nas"

      